name: build

on:
  workflow_dispatch:       # workflow can be run manually from the actions tab
  schedule:
    - cron: '0 3 * * 0'    # run workflow at 3am each sunday

jobs:    

  build:  
    runs-on: ${{ matrix.os }}    

    env:
      CMAKE_BUILD_TYPE: "${{ matrix.build_type }}"
      TARGET_SPEC: ${{ matrix.os }}-${{ matrix.build_type }}
      
    defaults:
      run:
        shell: bash
        
    steps:   
      - uses: actions/checkout@v3
      - run: ./build.sh 
      - uses: actions/upload-artifact@v3
        with:
          name: cocor-artifacts
          path: cocor.${{ matrix.os }}-${{ matrix.build_type }}*
          if-no-files-found: error 
 
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]      # , windows-2022]
        build_type: [debug, release]

  deploy-executables:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: cocor-artifacts
    
      - uses: ncipollo/release-action@v1
        with:
          tag: "v1.0.0"
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "cocor.macos-12-debug,cocor.macos-12-release"
          # token: ${{ secrets.GITHUB_TOKEN }}
    
   #   - uses: softprops/action-gh-release@v1
   #   # if: startsWith(github.ref, 'refs/tags/')
   #     with:
   #       files: |            
   #         #- cocor.macos-12-debug
   #         - cocor.macos-12-release
   #         #- cocor.ubuntu-22.04-debug
   #         - cocor.ubuntu-22.04-release
   #         #- cocor.windows-2022-debug.exe
   #         - cocor.windows-2022-release.exe

