name: build

on:
  workflow_call:       # workflow is reusable
  workflow_dispatch:   # workflow can be run manually from the actions tab

jobs:    

  ci:  
    runs-on: ${{ matrix.os }}    

    env:
      CMAKE_BUILD_TYPE: "${{ matrix.build_type }}"
      TARGET_SPEC: ${{ matrix.os }}-${{ matrix.build_type }}
      
    defaults:
      run:
        shell: bash
        
    steps:   
      - uses: actions/checkout@v3
      - run: ./build.sh 
      - uses: actions/upload-artifact@v3
        with:
          name: cocor-artifacts
          path: cocor.${{ matrix.os }}-${{ matrix.build_type }}*
 
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        build_type: [debug, release]


